# gaming-hospitality-iac
name: Upload Terraform Modules to JFrog
 
on:
  push:
    branches:
      - main
env:
  JF_RT_URL: https://mgmresorts.jfrog.io
  JFROG_USERNAME: 'arana@mgmresorts.com'
  RT_REPO_VIRTUAL: 'gaming-hospitality-iac-terraform-dev-virtual'
  JFROG_CLI_LOG_LEVEL: 'DEBUG' # DEBUG, INFO, WARN, ERROR
  RBv2_SIGNING_KEY: 'mgmkey'
  PACKAGE_SCOPE: '@mgmresorts'
  OIDC_PROVIDER_NAME: 'mgmri-commerce-oidc'
  DISABLE_JOB_SUMMARY: false;
  
permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: write # to push updates while version bump and publish to repo, read is fine if there is just read operation​
  security-events: write # Required for uploading code scanning.
  issues: read 
  
jobs:
  upload-to-jfrog:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
 
    - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        with:
          version: 2.72.2
          oidc-provider-name: ${{env.OIDC_PROVIDER_NAME}}
          # comment oidc-provider-name when you test locally on codespace with act, getting an error for "ACTION_*" variable,
          # and uncomment when you test on gitub runner
          disable-job-summary: false
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JFROG_CLI_RELEASES_REPO: '${{ env.JF_RT_URL }}/artifactory/${{ env.RT_REPO_VIRTUAL}}'
          JFROG_CLI_EXTRACTORS_REMOTE: '${{ env.JF_RT_URL }}/artifactory/${{ env.RT_REPO_VIRTUAL}}'
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
    - name: Upload all Terraform modules
      run: |
        jfrog rt u "modules/(**/*)" "$RT_REPO_VIRTUAL/"
 
