variables:
  postmanSecretsAzureSubscription: 'Guest Services Dev SP'
  postmanSecretsKeyVault: 'guestservicesprv-uw-kv-d'
  postmanEnvironmentPath: '$(Build.SourcesDirectory)/validationChecks/ows_dev.postman_environment.json'
  temporaryWhitelistIpToKeyVault: false
