name: 'Run Tests'

on:
  pull_request:
    branches: [ "develop", "preprod", "main" ]

env:
  JF_OIDC: 'mgmri-enterprise-oidc'
  JF_URL : https://mgmresorts.jfrog.io
  JF_REPO : shared-sre-services-eventGridProxy-virtual
  DOTNET_VERSION: 8.0.x

permissions:
  contents: read
  id-token: write

jobs:
  tests:
    name: Unit Testing
    runs-on: mgm-runner
    steps:
      - uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
          
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946
        id: setup-cli
        env:
          JF_URL: ${{ env.JF_URL }}
        with:
          oidc-provider-name: ${{ env.JF_OIDC }}

      - name: Config Nuget
        run: jf dotnet-config --repo-resolve=${{ env.JF_REPO }}

      - name: Restore Nuget Packages
        run: jf dotnet restore ${{ github.workspace }}/EventGridProxy/EventGridProxy.sln

      - name: DotNet Build
        run: jf dotnet build ${{ github.workspace }}/EventGridProxy/EventGridProxy.sln --configuration Release --no-restore
    
      - name: Run Unit Tests
        run: dotnet test ${{ github.workspace }}/EventGridProxy/EventGridProxy.Tests/EventGridProxy.Tests.csproj --configuration Release --no-restore
