name: Incremental GitHub Sync

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      source_org:
        description: Source Organization
        required: true
        default: MGMResorts
      target_org:
        description: Target Organization
        default: mgmri-commerce
        required: true
      repo_name:
        description: Repository Name
        default: apigee-ows-name
        required: true

jobs:
  sync:
    if: github.repository_owner == 'MGMResorts'
    runs-on: ubuntu-latest
    env:
      SOURCE_ORG: ${{ github.event.inputs.source_org || 'MGMResorts' }}
      TARGET_ORG: ${{ github.event.inputs.target_org || 'mgmri-commerce' }}
      REPO_NAME: ${{ github.event.inputs.repo_name || 'apigee-ows-name' }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Run Sync Script
        env:
          GITHUB_SOURCE_TOKEN: ${{ secrets.SOURCE_ADMIN_TOKEN }}
          GITHUB_DEST_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}
        run: |
          bash ./.github/scripts/github_migrate.sh
