name: Jfrog Xray audit

on:
  push:
    branches:
    - apigee-mtls
env:
  JF_URL: https://mgmresorts.jfrog.io
  JFROG_CLI_LOG_LEVEL: 'DEBUG' # DEBUG, INFO, WARN, ERROR
  OIDC_PROVIDER_NAME: 'test-exploration-oidc'
  DISABLE_JOB_SUMMARY: false

permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: write # to push updates while version bump and publish to repo, read is fine if there is just read operation​
  security-events: write # Required for uploading code scanning.
  issues: read

jobs:
  xray-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        ref: apigee-mtls


    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 2.76.1
        oidc-provider-name: ${{env.OIDC_PROVIDER_NAME}}
      env:
        JF_URL: ${{ env.JF_URL }}
        # JF_ACCESS_TOKEN: ${{ secrets.JF_TK }}
  
    - name: Run JFrog Xray Audit and Save Output
      continue-on-error: true
      run: |
        jf audit --format=table --extended-table=true --mvn=true --secrets=true --sast=true --sca=true --vuln=true --licenses=true --fail=false >> xray-audit-report.txt
   
    # - name: Scan
    #   continue-on-error: true
    #   run: |
    #     jf scan . --extended-table=true  
   
    # - name: Job Summary
    #   run: |
    #     echo '```' >> $GITHUB_STEP_SUMMARY
    #     cat xray-audit-report.txt >> $GITHUB_STEP_SUMMARY
    #     echo '```' >> $GITHUB_STEP_SUMMARY
    # - name: Upload Xray Audit Report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: xray-audit-report
    #     path: xray-audit-report.txt
    - name: Scan and Save Output
      continue-on-error: true
      run: |
        jf scan . --extended-table=true | tee scan-report.txt

    - name: Job Summary
      run: |
        echo '### Xray Audit Report' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat xray-audit-report.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo '' >> $GITHUB_STEP_SUMMARY
        echo '### Scan Report' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat scan-report.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Upload Xray Audit Report
      uses: actions/upload-artifact@v4
      with:
        name: xray-audit-report
        path: xray-audit-report.txt

    - name: Upload Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: scan-report
        path: scan-report.txt
